name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install audio dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libpulse-dev
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
    
    - name: Build for all platforms
      run: |
        # Create build directory
        mkdir -p build
        
        # Build for all platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/tuitar-linux-amd64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o build/tuitar-darwin-amd64 .
        
        # Make binaries executable
        chmod +x build/tuitar-linux-*
        chmod +x build/tuitar-darwin-*
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        files: build/*
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
